# Generated by Django 4.1.3 on 2022-11-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя. Максимум 20 символов', max_length=20)),
                ('last_name', models.CharField(help_text='Фамилия. Максимум 50 символов', max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Пользователь'), ('moderator', 'Модератор')], default='member', max_length=9)),
                ('age', models.PositiveIntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.location')),
            ],
        ),
    ]
