# Generated by Django 4.1.3 on 2022-12-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(help_text='Краткое описание. Максимум 1000 символов', max_length=1000, null=True),
        ),
    ]
