# Generated by Django 4.1.3 on 2022-11-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_author_ad_author_id_ad_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='category_id',
            new_name='category',
        ),
    ]
